apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AmirWeiser/opentelemetry-demo-gitops.git
    targetRevision: main
    path: helm/opentelemetry-demo
    helm:
      valueFiles:
        - values.yaml
        - values-eks.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: opentelemetry-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
