---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-demo-imageprovider
  labels:
    opentelemetry.io/name: opentelemetry-demo-imageprovider
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/component: imageprovider
    app.kubernetes.io/name: opentelemetry-demo-imageprovider
    app.kubernetes.io/version: "1.12.0"
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  replicas: {{ .Values.imageProvider.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      opentelemetry.io/name: opentelemetry-demo-imageprovider
  template:
    metadata:
      labels:
        opentelemetry.io/name: opentelemetry-demo-imageprovider
        app.kubernetes.io/instance: opentelemetry-demo
        app.kubernetes.io/component: imageprovider
        app.kubernetes.io/name: opentelemetry-demo-imageprovider
    spec:
      serviceAccountName: opentelemetry-demo
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: imageprovider
          image: "{{ .Values.imageProvider.image.repository }}:{{ .Values.imageProvider.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: service
          env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['app.kubernetes.io/component']
            - name: OTEL_COLLECTOR_NAME
              value: 'opentelemetry-demo-otelcol'
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: cumulative
            - name: IMAGE_PROVIDER_PORT
              value: "8081"
            - name: OTEL_COLLECTOR_PORT_GRPC
              value: "4317"
            - name: OTEL_COLLECTOR_HOST
              value: $(OTEL_COLLECTOR_NAME)
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=1.12.0
          resources:
            {{- toYaml .Values.imageProvider.resources | nindent 12 }}
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 15
